kind = "web"
previewPath = "/"
title = "UMKM Go"
version = "1.0.0"
id = "artifacts/umkm-go"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24591

[services.development]
run = "pnpm --filter @workspace/umkm-go run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/umkm-go", "run", "build" ]
publicDir = "artifacts/umkm-go/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24591"
BASE_PATH = "/"
